### ISSUE TITLE
Uncaught TypeError: $(...).fancytree is not a function, on node creation via paragraphs.

### ISSUE THREAD

**Issue by janvonmulert** [duartegarin/term_reference_fancytree#11]
I have a node (with a fancytree enabled term reference field) which can be referenced/added by another node through the paragraphs module.
Paragraphs allows node creation via an ajax form on the parent node. But the term reference picker doesn't show. It looks like the fancytree library is not available from within the ajax form.

In console:

`Uncaught TypeError: $(...).fancytree is not a function
    at new Drupal.TermReferenceFancyTree (<anonymous>:37:17)
    at HTMLDivElement.<anonymous> (<anonymous>:17:15)
    at Function.each (jquery.min.js?v=3.5.1:2)
    at S.fn.init.each (jquery.min.js?v=3.5.1:2)
    at Object.attach (<anonymous>:16:74)
    at drupal.js?v=8.9.1:25
    at Array.forEach (<anonymous>)
    at Object.Drupal.attachBehaviors (drupal.js?v=8.9.1:22)
    at HTMLDivElement.<anonymous> (ajax.js?v=8.9.1:562)
    at Function.each (jquery.min.js?v=3.5.1:2)`

**Comment by jaydub2099** [comment]
I can also confirm this issue. Clearly the library needs to be loaded when the add paragraph ajax action happens.

**Comment by jaydub2099** [comment]
I looked at the waterfall of JS files loaded via ajax when add paragraph ajax action happens and it's simply a case of the module tree.js file loading and being parsed before the fancytree external js file is loaded and parsed. Rather than try to find a way to make sure the fancytree JS is loaded before referenced in tree.js, I have this working by using a form alter on the node form that includes the paragraph(s) in question that have the ajax add paragraph action.

e.g inside a form alter:

if (in_array($nodeType, ['type_one', 'type_two', 'type_three'])) {
  $form['#attached']['library'][] = 'term_reference_fancytree/fancytree';
}

Obviously you'd want to implement your own logic, the key line here just being the $form['#attached'] item.
